// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// TemplateGeneratorUsecase is an autogenerated mock type for the TemplateGeneratorUsecase type
type TemplateGeneratorUsecase struct {
	mock.Mock
}

// UpdateTemplate provides a mock function with no fields
func (_m *TemplateGeneratorUsecase) UpdateTemplate() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdateTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTemplateGeneratorUsecase creates a new instance of TemplateGeneratorUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTemplateGeneratorUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TemplateGeneratorUsecase {
	mock := &TemplateGeneratorUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
