log:
  log_rotation_time: "hour"

  log_info_dir: "log"                 # Default is "log"
  log_info_name: "logger.log"         # Save log level greater or equal INFO, default is "logger.log"

  log_debug_dir: "log"                # Default is "log"
  log_debug_name: "logger_debug.log"  # Save log level less than INFO, default is "logger-debug.log" 

rabbitmq:
  rabbitmq_host: "amqp://admin:admin123@127.0.0.1:5672/"
  rabbitmq_queue: "queue"
  backup_filename: "rabbitBackupFile.txt"
  backup_folder: "./rabbitBackup"

kafka:
  kafka_addr: "localhost:29092"
  kafka_topic: "testTopic"
  kafka_group: "testGroup"
  kafka_partition: 0

tcp_server:
  tcp_addr: "0.0.0.0:9095"

tcp_client:
  tcp_server_url: "0.0.0.0:9095"
  server_name: "server"
  client_name: "client"

http_server:
  http_addr: "0.0.0.0:8080"

websocket:
  websocket_addr: "0.0.0.0:8888"

proxy_server:
  proxy_address: "0.0.0.0:9000"

grpc_server:
  grpc_addr: "192.168.114.61:10000"

grpc_client:
  grpc_server: "192.168.114.61:10000"

sql:
  sql_addr: "user:pass@tcp(127.0.0.1:3306)/classicmodels"

redis:
  redis_addr: "localhost:6379"
  redis_password: "123"

mail_client:
  mail_server: "smtp.example.com"
  mail_smtp_addr: "smtp.example.com:587"
  mail_username: "from@example.com"
  mail_password: "password"

# Do not share to anyone
secret_key: "your_secret_key"