// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GenerateBehaviors is an autogenerated mock type for the GenerateBehaviors type
type GenerateBehaviors struct {
	mock.Mock
}

// Generate provides a mock function with given fields:
func (_m *GenerateBehaviors) Generate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewGenerateBehaviors interface {
	mock.TestingT
	Cleanup(func())
}

// NewGenerateBehaviors creates a new instance of GenerateBehaviors. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGenerateBehaviors(t mockConstructorTestingTNewGenerateBehaviors) *GenerateBehaviors {
	mock := &GenerateBehaviors{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
